### ISSUE TITLE
missing STL for v1.1 controller and touchscreen 

### ISSUE THREAD

**Issue by rd636** [mokeylaser/MokeyLaserV1#2]
Please add your STL models for the MKS DCL32 controller and 3.5" touchscreen.

**Comment by mokeylaser** [comment]
I have added all files including the MKS DLC32 controller and touchscreen to the V1.1 folder.
https://github.com/mokeylaser/MokeyLaserV1/tree/main/MokeyLaser_v1.1
Thank you, and let me know of any other issues.

**Comment by rd636** [comment]
I don't know if you can direct message this way- but I thought I'd try.

Thank you for your github post and additional files.  I've may a 900x900
with some small tweaks.
If this email finds you and you reply, I'd be happy to share pics.

I'm having a bit of trouble getting my LT-4LDS-V2 80w LaserTree to fire,
but the build went well and it moves fast.

Sincerely,

RD636
