### ISSUE TITLE
STL was rendered icorrectly.

### ISSUE THREAD

**Issue by rd636** [mokeylaser/MokeyLaserV1#3]
Thank you so much for publishing the DLC parts.  I've started printing.  The display STL file looks like it has a model TFT inside by mistake.  Will you please repost. 
https://github.com/mokeylaser/MokeyLaserV1/tree/main/MokeyLaser_v1.1/Display Holder TS35-R-V2 v5.stl

**Comment by mokeylaser** [comment]
I reposted the file without the display or mounting screws (my apologies), and I added the bracket, which is needed to mount the display holder to the engraver frame.
